---
# tasks file for parasight_dbserver

- name: Include OS Family vars
  include_vars: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"


- include: install/main.yml

- include: service/main.yml

- include: config/main.yml

