---
# tasks file for parasight_webserver


- name: Include OS Family vars
  include_vars: "{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"


- include_tasks: install/main.yml

- include_tasks: service/main.yml

- include_tasks: config/main.yml

- include_tasks: app/main.yml

